### ISSUE TITLE
[Feature]: Implement stack  

### ISSUE THREAD

**Issue by opabhijeet** [OPCODE-Open-Spring-Fest/DSA_Dojo#1]
# Implement Stack
* You can use "stdexcept.h" for exception handling
* You have to implement stack **without using any other library** ( not even iostream )
* You have to implement the functions mentioned in DSA_DOJO/Medium/Day1/Stack.h
* You don't have to add any file and **only need to modify** DSA_DOJO/Medium/Day1/Stack.h
* Stack should be dynamic and should consist of Nodes
* Functions of the class should be defined outside the class
* You should handle all the exceptions that may occur
* You are free to add any other functionality 
* You should not delete anything in DSA_DOJO/Medium/Day1/Stack.h
* If your solution is found to be plagiarised heavy penalty would be imposed
* You would be given 4 working hours ( 1 Day ) to submit the solution 

### Functions that need to be implemented are:
* Stack()    --->   this is the default constructor
* Stack(T element)    --->  constructor to initialise stack with one number
* Stack(T arr[], int n)   --->  constructor to initialise stack from an array containing n elements, the first element of the array must be at the top of the stack
* const T& top()   --->  return element at top of the stack if it exists
* T pop()              --->  return element at top of stack and delete it
* void push(T element)    --->  insert element into the stack
* bool empty()      --->  return true if stack is empty and false otherwise
* int size()            --->  return number of elements present in the stack

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ankur-Dwivedi22** [comment]
@opabhijeet and @Roshu2003 Asssign me this issue.
