### ISSUE TITLE
[Feature]: Implement circular queue using linked list

### ISSUE THREAD

**Issue by opabhijeet** [OPCODE-Open-Spring-Fest/DSA_Dojo#11]
# Implement circular queue using linked list
* You can use "stdexcept.h" for exception handling
* You have to implement circular queue **without using any other library** ( not even iostream )
* You have to implement the functions mentioned in DSA_DOJO/Easy/CQueue2.h
* You don't have to add any file and **only need to modify** DSA_DOJO/Easy/CQueue2.h
* Circular queue should be dynamic and should consist of Nodes
* Functions of the class should be defined outside the class
* You should handle all the exceptions that may occur
* You are free to add any other functionality 
* You should not delete anything in DSA_DOJO/Easy/CQueue2.h
* If your solution is found to be plagiarised heavy penalty would be imposed
* You would be given 4 working hours ( 1 Day ) to submit the solution 

### Functions that need to be implemented are:
* CQueue()    --->    //default constructor
* CQueue(T element)    --->    //constructor to initialize queue with one number
* CQueue(T arr[],int n)    --->    //constructor to initialize queue from an array
* void push(T value)    --->    //inserts element into the queue
* T pop()    --->    //return element at front of queue and deletes it
* const T& front()    --->    //return element at front of the queue
* T size()    --->    //return true if queue is empty and false otherwise
* bool empty()    --->    //return true if queue is empty and false otherwise

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyamraj1643** [comment]
Kindly assign this to me.
