### ISSUE TITLE
[Feature]: Implement Circular with a fixed maximum size

### ISSUE THREAD

**Issue by opabhijeet** [OPCODE-Open-Spring-Fest/DSA_Dojo#4]
### So, what is it about?

# Implement Circular with a fixed maximum size
* You can use "stdexcept.h" for exception handling
* You have to implement queue **without using any other library** ( not even iostream )
* You have to implement the functions mentioned in Easy/Day1/CQueue.h
* You don't have to add any file and **only need to modify** Easy/Day1/CQueue.h
* Queue should have a fixed maximum size 
* Queue should have a default maximum size of 10 elements
* Functions of the class should be defined outside the class
* You should handle all the exceptions that may occur
* You are free to add any other functionality 
* You should not delete anything in Easy/Day1/CQueue.h
* If your solution is found to be plagiarised heavy penalty would be imposed
* You would be given 4 working hours ( 1 Day ) to submit the solution 

### Functions that need to be implemented are:
* CQueue(int s)    --->    constructor for creating circular queue object with default maximum size of 10 elements
* void push(T value)    --->    insert element into circular queue
* T pop()    --->    delete the element from the front of circular queue and return it
* const T& front()    --->    return element present at the front of the circular queue 
* int size()    --->    return number of elements present in an circular queue 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyamraj1643** [comment]
Kindly assign this task to me.

**Comment by Nidhi-Satyapriya** [comment]
Kindly assign this to me.
