### ISSUE TITLE
[Question]:Day10/Medium 

### ISSUE THREAD

**Issue by Roshu2003** [OPCODE-Open-Spring-Fest/DSA_Dojo#52]
### So, what is it about?

Visit the Medium/Day10 folder, check out the problem.txt file and solve the question.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutosh-3474** [comment]
@Roshu2003 kindly assign me this task

**Comment by neerajyadavrewa** [comment]
@Roshu2003  sir please assign this issue to me
