### ISSUE TITLE
[Question]: Party in Treeland 

### ISSUE THREAD

**Issue by Roshu2003** [OPCODE-Open-Spring-Fest/DSA_Dojo#8]
### So, what is it about?

# So, what is it about?

Visit the medium/day2 folder, check out the problem.txt file and solve the question.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rohityadav74** [comment]
@Roshu2003 please assign me this problem

**Comment by Roshu2003** [comment]
You have to complete this issue at the end of day..

**Comment by Ankur-Dwivedi22** [comment]
@opabhijeet & @Roshu2003 Kindly assign me this issue .

**Comment by Rishavalpha9** [comment]
@opabhijeet & @Roshu2003 Kindly assign me this issue .

**Comment by Roshu2003** [comment]
#close
